declare namespace Enum {
    declare enum ItemQuality {
        Poor = 0,
        Common = 1,
        Uncommon = 2,
        Rare = 3,
        Epic = 4,
        Legendary = 5,
        Artifact = 6,
        Heirloom = 7,
        WoWToken = 8
    }

    declare enum PlayerInteractionType {
        None = 0,
        TradePartner = 1,
        Item = 2,
        Gossip = 3,
        QuestGiver = 4,
        Merchant = 5,
        TaxiNode = 6,
        Trainer = 7,
        Banker = 8,
        AlliedRaceDetailsGiver = 9,
        GuildBanker = 10,
        Registrar = 11,
        Vendor = 12,
        PetitionVendor = 13,
        TabardVendor = 14,
        TalentMaster = 15,
        SpecializationMaster = 16,
        MailInfo = 17,
        SpiritHealer = 18,
        AreaSpiritHealer = 19,
        Binder = 20,
        Auctioneer = 21,
        StableMaster = 22,
        BattleMaster = 23,
        Transmogrifier = 24,
        LFGDungeon = 25,
        VoidStorageBanker = 26,
        BlackMarketAuctioneer = 27,
        AdventureMap = 28,
        WorldMap = 29,
        GarrArchitect = 30,
        GarrTradeskill = 31,
        GarrMission = 32,
        ShipmentCrafter = 33,
        GarrRecruitment = 34,
        GarrTalent = 35,
        Trophy = 36,
        PlayerChoice = 37,
        ArtifactForge = 38,
        ObliterumForge = 39,
        ScrappingMachine = 40,
        ContributionCollector = 41,
        AzeriteRespec = 42,
        IslandQueue = 43,
        ItemInteraction = 44,
        ChromieTime = 45,
        CovenantPreview = 46,
        AnimaDiversion = 47,
        LegendaryCrafting = 48,
        WeeklyRewards = 49,
        Soulbind = 50,
        CovenantSanctum = 51,
        NewPlayerGuide = 52,
        ItemUpgrade = 53,
        AdventureJournal = 54,
        Renown = 55,
        AzeriteForge = 56,
        PerksProgramVendor = 57,
        ProfessionsCraftingOrder = 58,
        Professions = 59,
        ProfessionsCustomerOrder = 60,
        TraitSystem = 61,
        BarbersChoice = 62,
        JailersTowerBuffs = 63,
        MajorFactionRenown = 64,
    }

    declare enum GarrisonFollowerType {
        FollowerType_6_0 = 1,
        FollowerType_6_2 = 2,
        FollowerType_7_0 = 4,
        FollowerType_8_0 = 22,
        FollowerType_9_0 = 123
    }
}
